
title: Link2Cyber Bootcamp
description: Learn cybersecurity through a structured 80-day journey using the LinksOS framework.

# Use GitHub Pages-compatible remote theme
remote_theme: just-the-docs/just-the-docs

url: https://benlinkous.github.io/link2cyber.com

# Just the Docs collection settings
just_the_docs:
  collections:
    80-days:
      name: 80 Days
      nav_fold: true

collections:
  80-days:
    output: true
    permalink: /80-days/:path/
    sort_by: nav_order

aux_links:
  GitHub Repo: https://github.com/benlinkous/link2cyber.com

nav_sort: case_insensitive
logo: "/assets/logo-metallic-silver.png"

callouts_level: quiet
callouts:
  highlight:
    color: yellow
  info:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red

search_enabled: true
search:
  heading_level: 2
  tokenizer_separator: /[\s/]+/

back_to_top: true
back_to_top_text: "Back to top"
