title: Link2Cyber Bootcamp
description: Learn cybersecurity through a structured 80-day journey using the LinksOS framework.
remote_theme: just-the-docs/just-the-docs

collections:
  80-days:
    output: true
    permalink: /80-days/:path/
    sort_by: nav_order

just_the_docs:
  collections:
    80-days:
      name: "80 DAYS"
      nav_fold: true

# Optional: Enable search
search_enabled: true
search:
  heading_level: 2
  tokenizer_separator: /[\s/]+/

# Optional: Customize callout boxes
callouts_level: quiet
callouts:
  highlight:
    color: yellow
  info:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red

# Optional: Back to top button
back_to_top: true
back_to_top_text: "Back to top"

# Optional: External links
aux_links:
  GitHub Repo
