title: Link2Cyber Bootcamp
description: Learn cybersecurity through a structured 80-day journey using the LinksOS framework.
theme: just-the-docs

url: https://benlinkous.github.io/link2cyber.com

logo: "/assets/logo-metallic-silver.png"

callouts_level: quiet
callouts:
  highlight:
    color: yellow
  info:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red

search_enabled: true
search:
  heading_level: 2
  tokenizer_separator: /[\s/]+/

back_to_top: true
back_to_top_text: "Back to top"

nav_sort: case_insensitive

aux_links:
  GitHub Repo: https://github.com/benlinkous/link2cyber.com

# Enable the 80-days collection
collections:
  80-days:
    output: true
    permalink: /80-days/:path/
    sort_by: nav_order

defaults:
  - scope:
      path: "80-days"
      type: "80-days"
    values:
      layout: default
      nav_order: 1

# This is your custom navigation
just_the_docs:
  nav:
    - index.md
    - Fundamentals:
        - 80-days/fundamentals.md
        - 80-days/LinksOS_Bootcamp_Day1.md
        - 80-days/LinksOS_Bootcamp_Day2.md
        - 80-days/LinksOS_Bootcamp_Day3.md
        - 80-days/LinksOS_Bootcamp_Day4.md
        - 80-days/LinksOS_Bootcamp_Day5.md
        - 80-days/LinksOS_Bootcamp_Day6.md
        - 80-days/LinksOS_Bootcamp_Day7.md
        - 80-days/LinksOS_Bootcamp_Day8.md
        - 80-days/LinksOS_Bootcamp_Day9.md
        - 80-days/LinksOS_Bootcamp_Day10.md
        - 80-days/LinksOS_Bootcamp_Day11.md
        - 80-days/LinksOS_Bootcamp_Day12.md
        - 80-days/LinksOS_Bootcamp_Day13.md
        - 80-days/LinksOS_Bootcamp_Day14.md
        - 80-days/LinksOS_Bootcamp_Day15.md
        - 80-days/LinksOS_Bootcamp_Day16.md
        - 80-days/LinksOS_Bootcamp_Day17.md
        - 80-days/LinksOS_Bootcamp_Day18.md
        - 80-days/LinksOS_Bootcamp_Day19.md
        - 80-days/LinksOS_Bootcamp_Day20.md
        - 80-days/LinksOS_Bootcamp_Day21.md
        - 80-days/LinksOS_Bootcamp_Day22.md
        - 80-days/LinksOS_Bootcamp_Day23.md
        - 80-days/LinksOS_Bootcamp_Day24.md
        - 80-days/LinksOS_Bootcamp_Day25.md
        - 80-days/LinksOS_Bootcamp_Day26.md
        - 80-days/LinksOS_Bootcamp_Day27.md
        - 80-days/LinksOS_Bootcamp_Day28.md
        - 80-days/LinksOS_Bootcamp_Day29.md
        - 80-days/LinksOS_Bootcamp_Day30.md
    - Basic Security:
        - 80-days/basic-security.md
        - 80-days/LinksOS_Bootcamp_Day31.md
        - 80-days/LinksOS_Bootcamp_Day32.md
        - 80-days/LinksOS_Bootcamp_Day33.md
        - 80-days/LinksOS_Bootcamp_Day34.md
        - 80-days/LinksOS_Bootcamp_Day35.md
        - 80-days/LinksOS_Bootcamp_Day36.md
        - 80-days/LinksOS_Bootcamp_Day37.md
        - 80-days/LinksOS_Bootcamp_Day38.md
        - 80-days/LinksOS_Bootcamp_Day39.md
        - 80-days/LinksOS_Bootcamp_Day40.md
        - 80-days/LinksOS_Bootcamp_Day41.md
        - 80-days/LinksOS_Bootcamp_Day42.md
        - 80-days/LinksOS_Bootcamp_Day43.md
        - 80-days/LinksOS_Bootcamp_Day44.md
        - 80-days/LinksOS_Bootcamp_Day45.md
        - 80-days/LinksOS_Bootcamp_Day46.md
        - 80-days/LinksOS_Bootcamp_Day47.md
        - 80-days/LinksOS_Bootcamp_Day48.md
        - 80-days/LinksOS_Bootcamp_Day49.md
        - 80-days/LinksOS_Bootcamp_Day50.md
        - 80-days/LinksOS_Bootcamp_Day51.md
        - 80-days/LinksOS_Bootcamp_Day52.md
        - 80-days/LinksOS_Bootcamp_Day53.md
        - 80-days/LinksOS_Bootcamp_Day54.md
        - 80-days/LinksOS_Bootcamp_Day55.md
        - 80-days/LinksOS_Bootcamp_Day56.md
        - 80-days/LinksOS_Bootcamp_Day57.md
        - 80-days/LinksOS_Bootcamp_Day58.md
        - 80-days/LinksOS_Bootcamp_Day59.md
        - 80-days/LinksOS_Bootcamp_Day60.md
    - Advanced Security:
        - 80-days/advanced-security.md
        - 80-days/LinksOS_Bootcamp_Day61.md
        - 80-days/LinksOS_Bootcamp_Day62.md
        - 80-days/LinksOS_Bootcamp_Day63.md
        - 80-days/LinksOS_Bootcamp_Day64.md
        - 80-days/LinksOS_Bootcamp_Day65.md
        - 80-days/LinksOS_Bootcamp_Day66.md
        - 80-days/LinksOS_Bootcamp_Day67.md
        - 80-days/LinksOS_Bootcamp_Day68.md
        - 80-days/LinksOS_Bootcamp_Day69.md
        - 80-days/LinksOS_Bootcamp_Day70.md
        - 80-days/LinksOS_Bootcamp_Day71.md
        - 80-days/LinksOS_Bootcamp_Day72.md
        - 80-days/LinksOS_Bootcamp_Day73.md
        - 80-days/LinksOS_Bootcamp_Day74.md
        - 80-days/LinksOS_Bootcamp_Day75.md
        - 80-days/LinksOS_Bootcamp_Day76.md
        - 80-days/LinksOS_Bootcamp_Day77.md
        - 80-days/LinksOS_Bootcamp_Day78.md
        - 80-days/LinksOS_Bootcamp_Day79.md
        - 80-days/LinksOS_Bootcamp_Day80.md
    - about.md
    - contact.md
    - lab-template.md
